# Generated by Django 2.2.5 on 2019-09-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='notica',
            new_name='noticia',
        ),
    ]
