# Generated by Django 2.2.5 on 2019-09-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20190926_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='intro',
            field=models.TextField(default='ola'),
            preserve_default=False,
        ),
    ]
