# Generated by Django 2.2.5 on 2019-09-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190926_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img2',
            field=models.CharField(default='https://images.noticiasautomotivas.com.br/img/f/hyundai-hb20-5-anos-NA-17.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
